server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server3:8763/eureka/
    fetch-registry: false
    register-with-eureka: false
  instance:
    appname: microservice-eureka-server
    hostname: server2
